#!/usr/bin/env python
#-*- coding: utf-8 -*-  
   
import paramiko  
import threading  
def ssh2(ip,username,passwd,cmd):  
    try:  
        ssh = paramiko.SSHClient()  
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())  
        ssh.connect(ip,22,username,passwd,timeout=5)  
        for m in cmd:  
            stdin, stdout, stderr = ssh.exec_command(m)  
#           stdin.write("Y")   
            out = stdout.readlines()  
            
            for o in out:  
                print o,  
        print '%s\tOK\n'%(ip)  
        ssh.close()  
    except :  
        print '%s\tError\n'%(ip)  
if __name__=='__main__':  
    cmd = ['ls'] 
    #批量登录，假设用户名密码相同
    username = "root"  
    passwd = "toor"    
    threads = []     
    print "Begin......"
    iplist = [‘10.21.2.193’,‘10.21.2.192’,‘10.21.2.187’]
    for ip in iplist:  
        #ip = '159.266.40.200' 
        a=threading.Thread(target=ssh2,args=(ip,username,passwd,cmd))   
        a.start() 
